stages:
  - build
variables:
  GITLAB_URL: gitlab.r53.cdn.tv1.eu:4567
  REGISTRY_IMAGE: $GITLAB_URL/devops/magewell-exporter
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $GITLAB_URL
  script:
    - export VERSION=$(docker run --rm -v "$PWD":/app:ro -w /app node:slim node -p "require('./package.json').version")
    - docker build -t $REGISTRY_IMAGE .
    - docker image tag "$REGISTRY_IMAGE:latest" "$REGISTRY_IMAGE:$VERSION"
    - docker push $REGISTRY_IMAGE:latest
    - docker push $REGISTRY_IMAGE:$VERSION

