stages:
  - build

docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.r53.cdn.tv1.eu:4567
  script:
    - docker login gitlab.r53.cdn.tv1.eu:4567
    - docker build -t gitlab.r53.cdn.tv1.eu:4567/devops/magewell-exporter:latest .
    - docker push gitlab.r53.cdn.tv1.eu:4567/devops/magewell-exporter:latest
